config/routes.rb
Rails.application.routes.draw do
  root "main#index"

  get 'main/index'
  get 'reports/index'
  get 'reports/report_by_category'
  get 'reports/report_by_dates'
  get 'reports/report'

  resources :operations
  resources :categories
  resources :reports
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :operations, dependent: :destroy

    validates :name, presence: true, uniqueness: true
    validates :description, presence: true

    paginates_per 10
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :category

  validates :amount, numericality: { greater_than: 0}
  validates :odate, presence: true
  validates :description, presence: true

  paginates_per 10

  def self.get_amounts_by_categories(start_date, end_date)
    categories_and_amount = Operation.joins(:category)
    .where("odate BETWEEN ? AND ?", start_date, end_date)
    .group('categories.name')
    .order('SUM(amount) DESC')
    .sum(:amount)
    return categories_and_amount
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.page(params[:page])
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to new_category_url(@category), notice: "Category '#{@category.name}' was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to edit_category_url(@category), notice: "Category '#{@category.name}' was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category '#{@category.name}' was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[ show edit update destroy ]

  # GET /operations or /operations.json
  def index
    @operations = Operation.order(odate: :desc).page(params[:page])
  end
  
  # GET /operations/1 or /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations or /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to new_operation_url(@operation), notice: "Operation was successfully created." }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to edit_operation_url(@operation), notice: "Operation was successfully updated." }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: "Operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operation_params
      params.require(:operation).permit(:amount, :odate, :description, :category_id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :validate_date, only: %i[ report ]

  def index
  end

  def report
    if params[:commit] == "Generate by date"
      redirect_to({action: "report_by_dates", start_date: @start_date, end_date: @end_date, category_id: params[:category_id]})
    else redirect_to({action: "report_by_category", start_date: @start_date, end_date: @end_date})
    end
  end

  def report_by_category
    @start = params[:start_date].to_s
    @end = params[:end_date].to_s
  
    @categories_and_amount = Operation.get_amounts_by_categories(@start, @end)
    @background_colors = (1..@categories_and_amount.count).map{"rgb(#{rand(255)}, #{rand(255)}, #{rand(255)})"}

    if @categories_and_amount == {}
      respond_to do |format|
        format.html { redirect_to reports_url, notice: "Operations for the period [#{params[:start_date]} - #{params[:end_date]}] not found." }
      end
    end
  end

  def report_by_dates
    @dates = []
    @amount = []
    @start = params[:start_date].to_s
    @end = params[:end_date].to_s

    unless params[:category_id] == ''
      operations = Operation.select(:amount, :odate, :category_id).where("odate >= :start_date AND odate <= :end_date AND category_id = :category_id", 
                          {start_date: params[:start_date], end_date: params[:end_date], category_id: params[:category_id]}).order(:odate)
      @category = operations[0].category.name
    else
      operations = Operation.select(:amount, :odate).where("odate >= :start_date AND odate <= :end_date", 
                          {start_date: params[:start_date], end_date: params[:end_date]}).order(:odate)
    end
    prev_date = ''
    operations.each do |oper|
      if prev_date == oper.odate.to_s
        @amount[-1] += oper.amount
      else
        @dates.append(oper.odate.to_s)
        @amount.append(oper.amount)
      end
      prev_date = oper.odate.to_s
    end
    if @amount == []
      respond_to do |format|
        format.html { redirect_to reports_url, notice: "Operations for the period [#{params[:start_date]} - #{params[:end_date]}] not found." }
      end
    end
  end

  def validate_date
    @start_date = params[:date_start]
    @end_date = params[:date_end]
    if params[:date_start] == ''
      @start_date = Operation.select(:odate).order(:odate).first.odate
    end
    if params[:date_end] == ''
      @end_date = Operation.select(:odate).order(:odate).last.odate
    end
    if @start_date > @end_date
      @start_date, @end_date = @end_date, @start_date
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <tr>
    <td><%= index + 1 %></td>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td>
      <div class="settings">
        <%= link_to "", edit_category_path(category), class: "btn btn-info bi bi-pencil-square settings-buttons" %>
        <%= button_to "", category, method: :delete, class: "btn btn-danger bi bi-trash3 settings-buttons" %>
      </div>
    </td>
  </tr>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: inline-flex" %>
    <%= form.text_field :name, placeholder: "Enter name" %>
  </div>

  <div>
    <%= form.label :description, style: "display: inline-flex" %>
    <%= form.text_field :description, placeholder: "Enter description" %>
  </div>
  <hr>
  <div>
    <%= submit_tag "Save", class: "btn btn-primary btn-md" %>
    <button type="reset" class="btn btn-secondary btn-md">Clear</button>
  </div>

<% end %>

app/views/categories/edit.html.erb
<div class="col-md-6 offset-md-3 col-lg-4 offset-lg-4">
  <div class="content-block content-block-head">
    <h1>Editing category</h1>
  </div>
</div>

<div class="col-md-6 offset-md-3 col-lg-4 offset-lg-4">
  <div class="content-block">
    <p style="color: green"><%= notice %></p>
    <%= render "form", category: @category %>
    <div class="col-5 offset-7">
      <%= link_to "Back to categories", categories_path, class: "btn btn-primary" %>
    </div>
  </div>
  <br>
</div>

app/views/categories/index.html.erb
<div class="col-md-8 offset-md-2">
  <div class="content-block content-block-head">
    <h1>Categories of expenses/incomes</h1>
  </div>
</div>

<div class="col-md-8 offset-md-2">
  <div class="content-block">
    <p style="color: green"><%= notice %></p>
    <div class="table">
      <table class="table table-hover" id="userTable">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Settings</th>
        </tr>
        </thead>
        <tbody>
          <% @categories.each_with_index do |category, index| %>
            <%= render partial: "category", locals: { category: category, index: index } %>
          <% end %>
        </tbody>
      </table>
      <%= paginate @categories %>
    </div>
    <hr>
    <div>
      <%= link_to "New category", new_category_path, class: "btn btn-primary btn-md" %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
  <div class="content-block content-block-head">
    <h1>New category</h1>
  </div>
</div>

<div class="col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
  <div class="content-block">
    <p style="color: green"><%= notice %></p>
    <%= render "form", category: @category %>
    <div class="col-4 offset-7">
      <%= link_to "Back to categories", categories_path, class: "btn btn-primary" %>
    </div>
  </div>
  <br>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finance Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="icon" type="image/jpg" href="/assets/icon.jpg">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <%= render "shared/navbar" %>

    <div class="wrapper">
      <main class="main">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </main>

      <%= render "shared/footer" %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/main/index.html.erb
<div class="col-md-12 col-lg-8 offset-lg-2">
    <div class="content-block content-block-head">
        <h2>Hello there! Get ready to take control of your finances with Personal Finance Manager.</h2>
    </div>
</div>

<div class="col-md-12 col-lg-8 offset-lg-2">
    <div class="content-block">
        <h5>
            The purpose of this web application is to help you control your financial transactions.<br><hr>
            In the application, you can create categories of operations that you have performed or are going to perform, view, change and delete them as needed.<br><hr>
            With the categories you've created, you can create and manage financial transactions you've made or plan to make.<br><hr>
            You can also create reports of operations for a certain period of time or by category.
        </h5>
    </div>
</div>

app/views/operations/_form.html.erb
<%= form_with(model: operation) do |form| %>
  <% if operation.errors.any? %>
    <div style="color: red">
      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: inline-flex" %>
    <%= form.text_field :amount, placeholder: "Enter sum" %>
  </div>

  <div>
    <%= form.label :date, style: "display: inline-flex" %>
    <%= form.date_field :odate, placeholder: "Select a date" %>
  </div>

  <div>
    <%= form.label :description, style: "display: inline-flex" %>
    <%= form.text_field :description, placeholder: "Enter description" %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: inline-flex" %>
    <%= form.collection_select :category_id, Category.order(:name), :id, :name, :prompt => "Select a category" %>
  </div>
  <hr>
  <div>
    <%= submit_tag "Save", class: "btn btn-primary" %>
    <button type="reset" class="btn btn-secondary">Clear</button>
  </div>
<% end %>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>">
  <tr>
    <td><%= index + 1 %></td>
    <td><%= operation.category.name %></td>
    <td><%= operation.amount %></td>
    <td><%= operation.odate %></td>
    <td><%= operation.description %></td>
    <td>
      <div class="settings">
        <%= link_to "", edit_operation_path(operation), class: "btn btn-info bi bi-pencil-square settings-buttons" %>
        <%= button_to "", operation, method: :delete, class: "btn btn-danger bi bi-trash3 settings-buttons" %>
      </div>
    </td>
  </tr>
</div>

app/views/operations/edit.html.erb
<div class="col-md-6 offset-md-3 col-lg-4 offset-lg-4">
  <div class="content-block content-block-head">
    <h1>Editing operation</h1>
  </div>
</div>

<div class="col-md-6 offset-md-3 col-lg-4 offset-lg-4">
  <div class="content-block">
    <p style="color: green"><%= notice %></p>
    <%= render "form", operation: @operation %>
    <div class="col-5 offset-7">
      <%= link_to "Back to operations", operations_path, class: "btn btn-primary" %>
    </div>
  </div>
  <br>
</div>

app/views/operations/index.html.erb
<div class="col-md-8 offset-md-2">
  <div class="content-block content-block-head">
    <h1>Operations</h1>
  </div>
</div>

<div class="col-md-8 offset-md-2">
  <div class="content-block">
    <p style="color: green"><%= notice %></p>
    <div class="table-responsive">
      <table class="table table-hover" id="userTable">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Category</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>
            <th scope="col">Description</th>
            <th scope="col">Settings</th>
        </tr>
        </thead>
        <tbody>
          <% @operations.each_with_index do |operation, index| %>
            <%= render partial: "operation", locals: { operation: operation, index: index } %>
          <% end %>
        </tbody>
      </table>
      <%= paginate @operations %>
    </div>
    <hr>
    <button type="button" class="btn btn-primary btn-md"><%= link_to "New operation", new_operation_path %></button>
  </div>
</div>

app/views/operations/new.html.erb
<div class="col-md-6 offset-md-3 col-lg-8 offset-lg-2 col-xl-4 offset-xl-4">
  <div class="content-block content-block-head">
    <h1>New operation</h1>
  </div>
</div>

<div class="col-md-6 offset-md-3 col-lg-8 offset-lg-2 col-xl-4 offset-xl-4">
  <div class="content-block">
    <p style="color: green"><%= notice %></p>
    <%= render "form", operation: @operation %>
    <div class="col-4 offset-7">
      <%= link_to "Back to operations", operations_path, class: "btn btn-primary" %>
    </div>
  </div>
  <br>
</div>

app/views/operations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @operation %>

<div>
  <%= link_to "Edit this operation", edit_operation_path(@operation) %> |
  <%= link_to "Back to operations", operations_path %>

  <%= button_to "Destroy this operation", @operation, method: :delete %>
</div>

app/views/reports/_form.html.erb
<%= form_with url: "reports/report", method: :get do |form| %>

    <div>
        <%= form.label "Date start", style: "display: inline-flex" %>
        <%= form.date_field :date_start, :placeholder => "Select a start date" %>
    </div>
  
    <div>
        <%= form.label "Date end", style: "display: inline-flex" %>
        <%= form.date_field :date_end, :placeholder => "Select a end date" %>
        </div>

    <div>
        <%= form.label :category_id, style: "display: inline-flex" %>
        <%= form.collection_select :category_id, Category.order(:name).pluck(:id, :name), :first, :second, :prompt => "Select a category" %>
    </div>
    <hr>
    <div>
        <%= submit_tag "Report by date", class: "btn btn-primary col-12 button_report", value: "Generate by date" %>
        <%= submit_tag "Report by category", class: "btn btn-success col-12 button_report", value: "Generate by categories" %>
        <hr>
        <button type="reset" class="btn btn-secondary col-12">Clear</button>
    </div>
  
<% end %>
  

app/views/reports/index.html.erb
<div class="col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
  <div class="content-block content-block-head">
      <h1>Reports</h1>
  </div>
</div>

<div class="col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
  <div class="content-block">
    <p style="color: red"><%= notice %></p>
    <%= render "form" %>
  </div>
  <br>
</div>

app/views/reports/report_by_category.html.erb
<div class="col-md-10 offset-md-1 col-lg-6 offset-lg-3">
  <div class="content-block content-block-head">
    <h1>Report by category</h1>
    <p> Operations for the period: <%= @start %> - <%= @end %>
    <div>
      <table class="table table-hover" id="userTable">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Categories</th>
            <th scope="col">Amounts</th>
        </tr>
        </thead>
        <tbody>
          <% @categories_and_amount.each_with_index do |(key, value), index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td><%= key %></td>
              <td><%= value %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="col-md-10 offset-md-1 col-lg-6 offset-lg-3">
  <div class="content-block">
    <div>
      <canvas id="myPieChart"></canvas>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  const ctx = document.getElementById('myPieChart').getContext('2d');
  const data = {
    labels: <%= raw @categories_and_amount.keys %>,
    datasets: [{
        label: 'Period: ' + '<%= @start %>' + ' - ' + '<%= @end %>',
        data: <%= @categories_and_amount.values %>,
        backgroundColor: <%= raw @background_colors %>,
        hoverOffset: 4
    }]
    };
    const config = {
        type: 'pie',
        data: data,
    };

  const myChart = new Chart(ctx, config)
</script>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

app/views/reports/report_by_dates.html.erb
<div class="col-md-8 offset-md-2">
  <div class="content-block content-block-head">
    <h1>Report by dates</h1>
    <p> Operations for the period: <%= @start %> - <%= @end %>
    <% if @category == nil %>
      <p> All categories </p>
    <% else %>
      <p> Category of operations: <%= @category %> </p>
    <% end %>
  </div>
</div>

<div class="col-md-8 offset-md-2">
  <div class="content-block">
    <div>
      <canvas id="myChart"></canvas>
    </div>
  </div>
  <br>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  const ctx = document.getElementById('myChart').getContext('2d');
  const data = {
    labels: <%= raw @dates %>,
    datasets: [{
      label: 'Period: ' + '<%= @start %>' + ' - ' + '<%= @end %>',
      data: <%= @amount %>,
      fill: false,
      borderColor: 'rgb(0, 0, 255)',
      tension: 0.1
    }]
  };
  const config = {
    type: 'line',
    data: data,
  };

  const myChart = new Chart(ctx, config)
</script>

app/views/shared/_footer.html.erb
<footer>
    <p>
        Powered by <a href="mailto:artem.kozatskyi@gmail.com">Artem Kozatskyi</a> © <span id="year"></span>
    </p>
    <a target="_blank" href="https://github.com/Kozatskiy-Artem"><i class="fa fa-3x fa-github"></i></a>
    <a target="_blank" href="https://www.linkedin.com/in/artem-kozatskyi/"><i class="fa fa-3x fa-linkedin"></i></a>
    <a target="_blank" href="tg://resolve?domain=kadjit13"><i class="fa fa-3x fa-paper-plane"></i></a>
    <a target="_blank" href="https://www.instagram.com/artem.kozatskiy13/?hl=ru"><i class="fa fa-3x fa-instagram"></i></a>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">Finance manager</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="/categories" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/categories">All categories</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/categories/new">Create category</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="/operations" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Operations
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/operations">All operations</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/operations/new">Create operation</a></li>
          </ul>
        </li>
        <li class="nav-item"><a class="nav-link active" href="/reports">Reports</a></li>
      </ul>
    </div>
  </div>
</nav>